--ELIMINACION DE TABLA TB_CNTCINFO (LOGIN)--
DROP TABLE TB_CNTCINFO;

--CREACION DE TABLA TB_CNTCINFO (LOGIN)--
CREATE TABLE TB_CNTCINFO 
(
  ID_TBCNTCINFO int IDENTITY(1,1) PRIMARY KEY,
  CONTACT_INFO VARCHAR(100) NULL,
  PHONE_N1 VARCHAR(15) NULL,
  PHONE_N2 VARCHAR(15) NULL,
  EMAIL VARCHAR(50) NULL,
  CREATE_DATE DATE NULL,
  MODIFY_DATE DATE NULL,
  CNTC_ENABLE CHAR(1) NULL,
  USER_WEB VARCHAR(15) NULL,
  PWD_WEB VARCHAR(15) NULL,
  WEB_ENABLE CHAR(1) NULL,
  WEB_LOCKED CHAR(1) NULL,
  ROL VARCHAR(10) NULL
);

--CREACION TABLA DE LOGIN
CREATE TABLE TB_LOGWEBSYS (
  ID_TBLGWBSYS int IDENTITY(1,1) PRIMARY KEY,
  TB_CNTCINFO_ID_TBCNTCINFO INT NOT NULL,
  SYSTEM_MODULE VARCHAR(150) NULL,
  EVENT_USER VARCHAR(50) NULL,
  STATUS VARCHAR(20) NULL,
  DATE_OPERATION DATE NULL,
  TIME_LOG TIME NULL,
  MSG_OPERATION VARCHAR(200) NULL);

--MODIFICACION DE TABLA TB_CNTCINFO (LOGIN)--
ALTER TABLE TBCNTCINFO ADD
  ID_TBCNTCINFO int IDENTITY(1,1) PRIMARY KEY,
  CONTACT_INFO VARCHAR(100) NULL,
  PHONE_N1 VARCHAR(15) NULL,
  PHONE_N2 VARCHAR(15) NULL,
  EMAIL VARCHAR(50) NULL,
  CREATE_DATE DATE NULL,
  MODIFY_DATE DATE NULL,
  CNTC_ENABLE CHAR(1) NULL,
  WEB_ENABLE CHAR(1) NULL,
  WEB_LOCKED CHAR(1) NULL;

--Insercion de registro en tabla de login (Modificado)
INSERT INTO TB_CNTCINFO (USER_WEB,PWD_WEB) VALUES ('Admin','123qwerty');

--Sentencia para crear BD
CREATE DATABASE PROYECTO
USE PROYECTO
GO
CREATE TABLE USUARIO(
USUARIO VARCHAR (20),
PASS VARCHAR (20),
ROL VARCHAR (20)
)
GO

--Sentencia para crear procedimiento almacenado Login (Original)
CREATE PROCEDURE SP_inicio_Sesion
@USER VARCHAR (20),
@PASS VARCHAR (20)
AS
SELECT ROL FROM USUARIO WHERE USUARIO=@USER AND PASS=@PASS
GO 

--Sentencia para ingresar en log de login
CREATE PROCEDURE SP_acceder
@ID_USER INT,
@FECHA DATE
AS
INSERT INTO TB_LOGWEBSYS (TB_CNTCINFO_ID_TBCNTCINFO,DATE_OPERATION) VALUES (@ID_USER,@FECHA);
GO 

--Sentencia para eliminar procedimiento almacenado
DROP PROCEDURE SP_acceder;

--Sentencia para eliminar procedimiento almacenado
DROP PROCEDURE SP_inicio_Sesion;

--Sentencia para crear procedimiento almacenado Login (Modificado)
CREATE PROCEDURE SP_inicio_Sesion
@USER VARCHAR (20),
@PASS VARCHAR (20)
AS
SELECT USER_WEB,'true' FROM TB_CNTCINFO WHERE USER_WEB=@USER AND PWD_WEB=@PASS
GO 

--Sentencia para traer ID
CREATE PROCEDURE SP_id
@USER VARCHAR (20)
AS
SELECT ID_TBCNTCINFO FROM TB_CNTCINFO WHERE USER_WEB=@USER
GO 

--Sentencia para traer BLOQUEO
CREATE PROCEDURE SP_bloqueo
@USER VARCHAR (20)
AS
SELECT WEB_LOCKED FROM TB_CNTCINFO WHERE USER_WEB=@USER
GO 

--Sentencia para traer BLOQUEO
CREATE PROCEDURE SP_activo
@USER VARCHAR (20)
AS
SELECT WEB_ENABLE FROM TB_CNTCINFO WHERE USER_WEB=@USER
GO 

--Sentencia para traer BLOQUEO
CREATE PROCEDURE SP_bloquear
@USER VARCHAR (20)
AS
UPDATE TB_CNTCINFO set WEB_LOCKED=1 WHERE USER_WEB=@USER
GO 

--Insercion de registro en tabla de login 
INSERT INTO USUARIO VALUES ('Admin','123qwerty','Administrador');

--Insercion de registro en tabla de login (Modificado) 
INSERT INTO TB_CNTCINFO VALUES ('Admin','123qwerty');

--Insercion de registro en tabla de login (Modificado) 
INSERT INTO TB_CLIENT (USER_WEB,PWD_WEB) VALUES ('Admin','123qwerty');

--Consulta de usuarios tabla login
SELECT ROL FROM USUARIO WHERE USUARIO='Admin' AND PASS='123qwerty';

--Consulta de usuarios tabla login (Modificada)
SELECT ROL FROM TB_CNTCINFO WHERE USER_WEB='Admin' AND PWD_WEB='123qwerty';

--Limpia la tabla USUARIOS
TRUNCATE USUARIOS;