--Sentencia para crear procedimiento almacenado Login (Modificado)
CREATE PROCEDURE SP_inicio_Sesion
@USER VARCHAR (20),
@PASS VARCHAR (20)
AS
SELECT USER_WEB,'true' FROM TB_CNTCINFO WHERE USER_WEB=@USER AND PWD_WEB=@PASS
GO 

--Sentencia para traer ID
CREATE PROCEDURE SP_id
@USER VARCHAR (20)
AS
SELECT ID_TBCNTCINFO FROM TB_CNTCINFO WHERE USER_WEB=@USER
GO 

--Sentencia para ingresar en log de login
CREATE PROCEDURE SP_acceder
@ID_USER INT,
@FECHA DATE
AS
INSERT INTO TB_LOGWEBSYS (TB_CNTCINFO_ID_TBCNTCINFO,DATE_OPERATION) VALUES (@ID_USER,@FECHA);
GO 

--Sentencia para traer BLOQUEO
CREATE PROCEDURE SP_bloqueo
@USER VARCHAR (20)
AS
SELECT WEB_LOCKED FROM TB_CNTCINFO WHERE USER_WEB=@USER
GO 

--Sentencia para traer BLOQUEO
CREATE PROCEDURE SP_activo
@USER VARCHAR (20)
AS
SELECT WEB_ENABLE FROM TB_CNTCINFO WHERE USER_WEB=@USER
GO 

--Sentencia para traer BLOQUEO
CREATE PROCEDURE SP_bloquear
@USER VARCHAR (20)
AS
UPDATE TB_CNTCINFO set WEB_LOCKED=1 WHERE USER_WEB=@USER
GO 